- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - 'vars.yaml'
  vars:
    token: "{{ lookup('file', 'token.key') }}"
  tasks:
    - name: Wait for SSH to be available
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: Check if node is already bootsrapped
      stat:
        path: /var/lib/bashible
      register: bootstrapped

    - name: Get bootstrap secret
      uri:
        url: "https://{{ kube_apiserver }}:6443/api/v1/namespaces/d8-cloud-instance-manager/secrets/manual-bootstrap-for-{{ node_group }}"
        return_content: yes
        method: GET
        status_code: 200
        body_format: json
        headers:
          Authorization: "Bearer {{ token }}"
        validate_certs: no
      register: bootstrap_secret
      when: bootstrapped.stat.exists == False

    - name: Run bootstrap.sh
      shell: "{{ bootstrap_secret.json.data['bootstrap.sh'] | b64decode }}"
      ignore_errors: yes
      when: bootstrapped.stat.exists == False

    - name: Run bootstrap.sh
      shell: "/var/lib/bashible/bootstrap.sh > /root/log.txt 2>&1"
      ignore_errors: yes
      when: bootstrapped.stat.exists == False

    - name: wait
      wait_for_connection:
        delay: 60
      when: bootstrapped.stat.exists == False