locals {
  machine_map = {
    machines = {
      master-1 = {
        id                  = "201"
        name                = "master-1"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.201"
        gateway             = "192.168.4.1"
        description         = "master-1 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "master"
      }
      master-2 = {
        id                  = "202"
        name                = "master-2"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.202"
        gateway             = "192.168.4.1"
        description         = "master-2 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "master"
      }
      front-1 = {
        id                  = "203"
        name                = "front-1"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 8192
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.203"
        gateway             = "192.168.4.1"
        description         = "front-1 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "frontend"
      }
      system-0 = {
        id                  = "204"
        name                = "system-0"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.204"
        gateway             = "192.168.4.1"
        description         = "systen-0 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "system"
      }
      system-1 = {
        id                  = "205"
        name                = "system-1"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.205"
        gateway             = "192.168.4.1"
        description         = "system-1 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "system"
      }
      worker-0 = {
        id                  = "206"
        name                = "worker-0"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.206"
        gateway             = "192.168.4.1"
        description         = "worker-0 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "worker"
      }
      worker-1 = {
        id                  = "207"
        name                = "worker-1"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.207"
        gateway             = "192.168.4.1"
        description         = "worker-1 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "worker"
      }
      worker-2 = {
        id                  = "208"
        name                = "worker-2"
        target_node         = "pve-pr"
        qemu_os             = "other"
        os_type             = "cloud-init"
        agent               = 1
        full_clone          = true
        template            = "ubuntu-cloud-init"
        cpu                 = "kvm64"
        cores               = 8
        socket              = 1
        memory              = 16384
        scsihw              = "virtio-scsi-pci"
        storage             = "100G"
        ip_address          = "192.168.4.208"
        gateway             = "192.168.4.1"
        description         = "worker-2 node"
        ssh_user            = "admin"
        disk_type           = "virtio"
        storage_dev         = "fast"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "password"
        automatic_reboot    = true
        network_firewall    = false
        dns_servers         = "8.8.8.8 127.0.0.1"
        ansible_playbook    = "./deckhouse/deckhouse-nodes.yml"
        node_group          = "worker"
      }
    }
  }
  machines = lookup(local.machine_map, "machines", {})
}
